export * as Admin from '@/modules/admin'
export * as Approval from '@/modules/approval'
export * as Auth from '@/modules/auth'
export * as Config from '@/modules/config'
export * from '@/modules/core/module-registry'
export * as Coordination from '@/modules/coordination'
export * as Defects from '@/modules/defects'
export * as Hr from '@/modules/hr'
export * as Kpi from '@/modules/kpi'
export * as Maintenance from '@/modules/maintenance'
export * as Navigation from '@/modules/navigation/dashboard'
export * as Overtime from '@/modules/overtime'
export * as Permissions from '@/modules/permissions'
export * as Production from '@/modules/production'
export * as Reports from '@/modules/reports'
