BEGIN;

UPDATE public.profiles SET role = 'TEAM_LEADER' WHERE role = 'SUPERVISOR';
UPDATE public.profiles SET role = 'TEAM_LEADER' WHERE role = 'USER';

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('ADMIN', 'MANAGER', 'WORKSHOP_MANAGER', 'TEAM_LEADER', 'MAINTENANCE', 'COORDINATION', 'SALES', 'HR'));

UPDATE public.role_tab_permissions SET role = 'TEAM_LEADER' WHERE role = 'SUPERVISOR';
UPDATE public.role_tab_permissions SET role = 'TEAM_LEADER' WHERE role = 'USER';

ALTER TABLE public.role_tab_permissions DROP CONSTRAINT IF EXISTS role_tab_permissions_role_check;
ALTER TABLE public.role_tab_permissions
  ADD CONSTRAINT role_tab_permissions_role_check
  CHECK (role IN ('ADMIN', 'MANAGER', 'WORKSHOP_MANAGER', 'TEAM_LEADER', 'MAINTENANCE', 'COORDINATION', 'SALES', 'HR'));

INSERT INTO public.role_tab_permissions (role, permission_key, level)
VALUES
  ('ADMIN', 'production', 'edit'),
  ('ADMIN', 'maintenance', 'edit'),
  ('ADMIN', 'coordination', 'edit'),
  ('ADMIN', 'administration', 'edit'),
  ('ADMIN', 'report', 'edit'),
  ('ADMIN', 'admin', 'edit'),
  ('ADMIN', 'maintenance.breakdowns', 'edit'),
  ('ADMIN', 'maintenance.schedule', 'edit'),
  ('ADMIN', 'maintenance.drawings', 'edit'),
  ('ADMIN', 'maintenance.surveys', 'edit'),
  ('ADMIN', 'maintenance.machines', 'edit'),
  ('ADMIN', 'coordination.delivery', 'edit'),
  ('ADMIN', 'coordination.findings5s', 'edit'),
  ('ADMIN', 'coordination.reports', 'edit'),
  ('ADMIN', 'administration.overtime', 'edit'),
  ('ADMIN', 'administration.hr', 'edit'),
  ('ADMIN', 'administration.findings5s', 'edit'),
  ('ADMIN', 'administration.iso', 'edit'),
  ('ADMIN', 'admin.users', 'edit'),
  ('ADMIN', 'admin.kpi-settings', 'edit'),
  ('MANAGER', 'production', 'edit'),
  ('MANAGER', 'maintenance', 'edit'),
  ('MANAGER', 'coordination', 'edit'),
  ('MANAGER', 'administration', 'edit'),
  ('MANAGER', 'report', 'view'),
  ('MANAGER', 'admin', 'invisible'),
  ('MANAGER', 'maintenance.breakdowns', 'edit'),
  ('MANAGER', 'maintenance.schedule', 'edit'),
  ('MANAGER', 'maintenance.drawings', 'edit'),
  ('MANAGER', 'maintenance.surveys', 'edit'),
  ('MANAGER', 'maintenance.machines', 'edit'),
  ('MANAGER', 'coordination.delivery', 'edit'),
  ('MANAGER', 'coordination.findings5s', 'edit'),
  ('MANAGER', 'coordination.reports', 'edit'),
  ('MANAGER', 'administration.overtime', 'edit'),
  ('MANAGER', 'administration.hr', 'edit'),
  ('MANAGER', 'administration.findings5s', 'edit'),
  ('MANAGER', 'administration.iso', 'edit'),
  ('MANAGER', 'admin.users', 'invisible'),
  ('MANAGER', 'admin.kpi-settings', 'invisible'),
  ('WORKSHOP_MANAGER', 'production', 'edit'),
  ('WORKSHOP_MANAGER', 'maintenance', 'view'),
  ('WORKSHOP_MANAGER', 'coordination', 'view'),
  ('WORKSHOP_MANAGER', 'administration', 'view'),
  ('WORKSHOP_MANAGER', 'report', 'view'),
  ('WORKSHOP_MANAGER', 'admin', 'invisible'),
  ('WORKSHOP_MANAGER', 'maintenance.breakdowns', 'view'),
  ('WORKSHOP_MANAGER', 'maintenance.schedule', 'view'),
  ('WORKSHOP_MANAGER', 'maintenance.drawings', 'view'),
  ('WORKSHOP_MANAGER', 'maintenance.surveys', 'view'),
  ('WORKSHOP_MANAGER', 'maintenance.machines', 'view'),
  ('WORKSHOP_MANAGER', 'coordination.delivery', 'view'),
  ('WORKSHOP_MANAGER', 'coordination.findings5s', 'view'),
  ('WORKSHOP_MANAGER', 'coordination.reports', 'view'),
  ('WORKSHOP_MANAGER', 'administration.overtime', 'edit'),
  ('WORKSHOP_MANAGER', 'administration.hr', 'view'),
  ('WORKSHOP_MANAGER', 'administration.findings5s', 'edit'),
  ('WORKSHOP_MANAGER', 'administration.iso', 'view'),
  ('WORKSHOP_MANAGER', 'admin.users', 'invisible'),
  ('WORKSHOP_MANAGER', 'admin.kpi-settings', 'invisible'),
  ('TEAM_LEADER', 'production', 'edit'),
  ('TEAM_LEADER', 'maintenance', 'invisible'),
  ('TEAM_LEADER', 'coordination', 'view'),
  ('TEAM_LEADER', 'administration', 'edit'),
  ('TEAM_LEADER', 'report', 'view'),
  ('TEAM_LEADER', 'admin', 'invisible'),
  ('TEAM_LEADER', 'maintenance.breakdowns', 'invisible'),
  ('TEAM_LEADER', 'maintenance.schedule', 'invisible'),
  ('TEAM_LEADER', 'maintenance.drawings', 'invisible'),
  ('TEAM_LEADER', 'maintenance.surveys', 'invisible'),
  ('TEAM_LEADER', 'maintenance.machines', 'invisible'),
  ('TEAM_LEADER', 'coordination.delivery', 'view'),
  ('TEAM_LEADER', 'coordination.findings5s', 'edit'),
  ('TEAM_LEADER', 'coordination.reports', 'view'),
  ('TEAM_LEADER', 'administration.overtime', 'edit'),
  ('TEAM_LEADER', 'administration.hr', 'view'),
  ('TEAM_LEADER', 'administration.findings5s', 'edit'),
  ('TEAM_LEADER', 'administration.iso', 'view'),
  ('TEAM_LEADER', 'admin.users', 'invisible'),
  ('TEAM_LEADER', 'admin.kpi-settings', 'invisible'),
  ('MAINTENANCE', 'production', 'invisible'),
  ('MAINTENANCE', 'maintenance', 'edit'),
  ('MAINTENANCE', 'coordination', 'invisible'),
  ('MAINTENANCE', 'administration', 'invisible'),
  ('MAINTENANCE', 'report', 'view'),
  ('MAINTENANCE', 'admin', 'invisible'),
  ('MAINTENANCE', 'maintenance.breakdowns', 'edit'),
  ('MAINTENANCE', 'maintenance.schedule', 'edit'),
  ('MAINTENANCE', 'maintenance.drawings', 'edit'),
  ('MAINTENANCE', 'maintenance.surveys', 'edit'),
  ('MAINTENANCE', 'maintenance.machines', 'edit'),
  ('MAINTENANCE', 'coordination.delivery', 'invisible'),
  ('MAINTENANCE', 'coordination.findings5s', 'invisible'),
  ('MAINTENANCE', 'coordination.reports', 'invisible'),
  ('MAINTENANCE', 'administration.overtime', 'invisible'),
  ('MAINTENANCE', 'administration.hr', 'invisible'),
  ('MAINTENANCE', 'administration.findings5s', 'invisible'),
  ('MAINTENANCE', 'administration.iso', 'invisible'),
  ('MAINTENANCE', 'admin.users', 'invisible'),
  ('MAINTENANCE', 'admin.kpi-settings', 'invisible'),
  ('COORDINATION', 'production', 'invisible'),
  ('COORDINATION', 'maintenance', 'invisible'),
  ('COORDINATION', 'coordination', 'edit'),
  ('COORDINATION', 'administration', 'invisible'),
  ('COORDINATION', 'report', 'view'),
  ('COORDINATION', 'admin', 'invisible'),
  ('COORDINATION', 'maintenance.breakdowns', 'invisible'),
  ('COORDINATION', 'maintenance.schedule', 'invisible'),
  ('COORDINATION', 'maintenance.drawings', 'invisible'),
  ('COORDINATION', 'maintenance.surveys', 'invisible'),
  ('COORDINATION', 'maintenance.machines', 'invisible'),
  ('COORDINATION', 'coordination.delivery', 'edit'),
  ('COORDINATION', 'coordination.findings5s', 'edit'),
  ('COORDINATION', 'coordination.reports', 'edit'),
  ('COORDINATION', 'administration.overtime', 'invisible'),
  ('COORDINATION', 'administration.hr', 'invisible'),
  ('COORDINATION', 'administration.findings5s', 'invisible'),
  ('COORDINATION', 'administration.iso', 'invisible'),
  ('COORDINATION', 'admin.users', 'invisible'),
  ('COORDINATION', 'admin.kpi-settings', 'invisible'),
  ('SALES', 'production', 'invisible'),
  ('SALES', 'maintenance', 'invisible'),
  ('SALES', 'coordination', 'view'),
  ('SALES', 'administration', 'invisible'),
  ('SALES', 'report', 'view'),
  ('SALES', 'admin', 'invisible'),
  ('SALES', 'maintenance.breakdowns', 'invisible'),
  ('SALES', 'maintenance.schedule', 'invisible'),
  ('SALES', 'maintenance.drawings', 'invisible'),
  ('SALES', 'maintenance.surveys', 'invisible'),
  ('SALES', 'maintenance.machines', 'invisible'),
  ('SALES', 'coordination.delivery', 'view'),
  ('SALES', 'coordination.findings5s', 'invisible'),
  ('SALES', 'coordination.reports', 'view'),
  ('SALES', 'administration.overtime', 'invisible'),
  ('SALES', 'administration.hr', 'invisible'),
  ('SALES', 'administration.findings5s', 'invisible'),
  ('SALES', 'administration.iso', 'invisible'),
  ('SALES', 'admin.users', 'invisible'),
  ('SALES', 'admin.kpi-settings', 'invisible'),
  ('HR', 'production', 'invisible'),
  ('HR', 'maintenance', 'invisible'),
  ('HR', 'coordination', 'invisible'),
  ('HR', 'administration', 'edit'),
  ('HR', 'report', 'view'),
  ('HR', 'admin', 'invisible'),
  ('HR', 'maintenance.breakdowns', 'invisible'),
  ('HR', 'maintenance.schedule', 'invisible'),
  ('HR', 'maintenance.drawings', 'invisible'),
  ('HR', 'maintenance.surveys', 'invisible'),
  ('HR', 'maintenance.machines', 'invisible'),
  ('HR', 'coordination.delivery', 'invisible'),
  ('HR', 'coordination.findings5s', 'invisible'),
  ('HR', 'coordination.reports', 'invisible'),
  ('HR', 'administration.overtime', 'edit'),
  ('HR', 'administration.hr', 'edit'),
  ('HR', 'administration.findings5s', 'edit'),
  ('HR', 'administration.iso', 'edit'),
  ('HR', 'admin.users', 'invisible'),
  ('HR', 'admin.kpi-settings', 'invisible')
ON CONFLICT (role, permission_key) DO UPDATE
SET level = EXCLUDED.level;

COMMIT;
